'use client'
import React from "react";
import {motion} from 'framer-motion'

const Pattern = () => {
  return (
    <svg
    className="absolute -z-10 -bottom-5 w-[400px] lg:w-full "
      width="801"
      height="164"
      viewBox="0 0 801 164"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <rect
        x="1"
        y="1"
        width="50"
        height="50"
        stroke="#D49CFF"
        strokeOpacity="0.4"
      />
      <rect
        x="57"
        y="1"
        width="50"
        height="50"
        stroke="#D49CFF"
        strokeOpacity="0.4"
      />
      <rect
        x="113"
        y="1"
        width="50"
        height="50"
        stroke="#D49CFF"
        strokeOpacity="0.4"
      />
      <rect
        x="169"
        y="1"
        width="50"
        height="50"
        stroke="#D49CFF"
        strokeOpacity="0.4"
      />
      <rect
        x="225"
        y="1"
        width="50"
        height="50"
        stroke="#D49CFF"
        strokeOpacity="0.4"
      />
      <rect
        x="281"
        y="1"
        width="50"
        height="50"
        stroke="#D49CFF"
        strokeOpacity="0.4"
      />
      <rect
        x="337"
        y="1"
        width="50"
        height="50"
        stroke="#D49CFF"
        strokeOpacity="0.4"
      />
      <rect
        x="393"
        y="1"
        width="50"
        height="50"
        stroke="#D49CFF"
        strokeOpacity="0.4"
      />
      <rect
        x="449"
        y="1"
        width="50"
        height="50"
        stroke="#D49CFF"
        strokeOpacity="0.4"
      />
      <rect
        x="505"
        y="1"
        width="50"
        height="50"
        stroke="#D49CFF"
        strokeOpacity="0.4"
      />
      <rect
        x="561"
        y="1"
        width="50"
        height="50"
        stroke="#D49CFF"
        strokeOpacity="0.4"
      />
      <rect
        x="617"
        y="1"
        width="50"
        height="50"
        stroke="#D49CFF"
        strokeOpacity="0.4"
      />
      <rect
        x="673"
        y="1"
        width="50"
        height="50"
        stroke="#D49CFF"
        strokeOpacity="0.4"
      />
      <rect
        x="729"
        y="1"
        width="50"
        height="50"
        stroke="#D49CFF"
        strokeOpacity="0.4"
      />
      <rect
        x="1"
        y="57"
        width="50"
        height="50"
        stroke="#D49CFF"
        strokeOpacity="0.4"
      />
      <rect
        x="57"
        y="57"
        width="50"
        height="50"
        stroke="#D49CFF"
        strokeOpacity="0.4"
      />
      <rect
        x="113"
        y="57"
        width="50"
        height="50"
        stroke="#D49CFF"
        strokeOpacity="0.4"
      />
      <rect
        x="169"
        y="57"
        width="50"
        height="50"
        stroke="#D49CFF"
        strokeOpacity="0.4"
      />
      <rect
        x="225"
        y="57"
        width="50"
        height="50"
        stroke="#D49CFF"
        strokeOpacity="0.4"
      />
      <rect
        x="281"
        y="57"
        width="50"
        height="50"
        stroke="#D49CFF"
        strokeOpacity="0.4"
      />
      <rect
        x="337"
        y="57"
        width="50"
        height="50"
        stroke="#D49CFF"
        strokeOpacity="0.4"
      />
      <rect
        x="393"
        y="57"
        width="50"
        height="50"
        stroke="#D49CFF"
        strokeOpacity="0.4"
      />
      <rect
        x="449"
        y="57"
        width="50"
        height="50"
        stroke="#D49CFF"
        strokeOpacity="0.4"
      />
      <rect
        x="505"
        y="57"
        width="50"
        height="50"
        stroke="#D49CFF"
        strokeOpacity="0.4"
      />
      <rect
        x="561"
        y="57"
        width="50"
        height="50"
        stroke="#D49CFF"
        strokeOpacity="0.4"
      />
      <rect
        x="617"
        y="57"
        width="50"
        height="50"
        stroke="#D49CFF"
        strokeOpacity="0.4"
      />
      <rect
        x="673"
        y="57"
        width="50"
        height="50"
        stroke="#D49CFF"
        strokeOpacity="0.4"
      />
      <rect
        x="729"
        y="57"
        width="50"
        height="50"
        stroke="#D49CFF"
        strokeOpacity="0.4"
      />
      <rect
        x="1"
        y="113"
        width="50"
        height="50"
        stroke="#D49CFF"
        strokeOpacity="0.4"
      />
      <rect
        x="57"
        y="113"
        width="50"
        height="50"
        stroke="#D49CFF"
        strokeOpacity="0.4"
      />
      <rect
        width="50"
        height="50"
        stroke="#D49CFF"
        strokeOpacity="0.4"
      />
    </svg>
  );
};

export default Pattern;
